[metadata]
name = greepbot
version = 3.0.3
summary = A discord bot that posts images and gifs of the legendary Geordie Greep.
home_page = https://github.com/JSheare/GreepBot
author = Jacob Shearer
author_email = jacob.shearer6912@gmail.com

[options]
packages =
    greepbot
    greepbot/config
    greepbot/data
    greepbot/helpers
    greepbot/startup
    greepbot/validation
python_requires = >=3.10
install_requires =
    discord.py[voice]
    platformdirs
    pydantic
    numpy

[options.entry_points]
console_scripts =
    greepbot = greepbot.main:main

[options.package_data]
greepbot =
    config/greepbot.ini
    data/*.png
    data/*.txt
    data/*.json
    data/*.gif
    data/*.mp3
	